In [2]:
import numpy as np;

In [ ]:
# Normal Array in numpy
arrayNormal = np.array([1,2,3,4])

print(arrayNormal);

array = arrayNormal * 2;

print(arrayNormal);

[1 2 3 4]
[2 4 6 8]


In [ ]:
# Multi dimensional array
array = np.array([[
            ['A','B','C'],
            ['D','E','F'],
            ['G','H','I']
    ],[
            ['A','B','C'],
            ['D','E','F'],
            ['P','H','I']
    ],[
            ['A','B','C'],
            ['D','E','F'],
            ['G','H','I']
    ]]);
print(array.ndim); # 3
print(array.shape);

# Multidimensional Indexing
print(array[1][2][0]); # P

# Concatenation
print(array[1][2][0] + array[1][2][2] + array[0][2][0]);

3
(3, 3, 3)
P
PIG


In [ ]:
arrayEr = np.array([[
            ['A','B','C'],
            ['D','E','F'],
            ['G','I']
    ]]);
print(arrayEr.ndim); 
# Error : ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 3) + inhomogeneous part.

In [23]:
# Slicing
array =  np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,15]
])
# array[start:end:step]

print("Row Selection")
sliceR = array[0:4:2];
print(sliceR);

print("Column Selection")
sliceC = array[:,0:3];
print(sliceC);

print("Row and Column Selection")
sliceRC = array[0:2,1:3:2];
print(sliceRC);

Row Selection
[[ 1  2  3  4]
 [ 9 10 11 12]]
Column Selection
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
Row and Column Selection
[[2]
 [6]]


In [ ]:
# Scalar Arithemetic

array = np.array([1,2,3,4]);
print(array + 2); # - , *, /, **

[3 4 5 6]


In [ ]:
# Vectorized Math functions
array = np.array([1,2,3,4]);

# np.sqrt() 
# np.round()
# np.floor()
# np.ceil()
# np.pi - no ()


# Example usage
radius = np.array([5,10,15,20,25]);

area = np.pi * radius ** 2;
perimeter = 2 * np.pi * radius;
volume = np.pi * radius ** 3;

print("Perimeter ",np.round(perimeter));
print("Area ",np.round(area));
print("Volume",np.round(volume));

Perimeter  [ 31.  63.  94. 126. 157.]
Area  [  79.  314.  707. 1257. 1963.]
Volume [  393.  3142. 10603. 25133. 49087.]


In [21]:
# Operators and Comparisons

array = np.array([1,2,3,4]);
array2 = np.array([5,6,7,8]);

print(array == array2);
print(array > array2);

print(array2 > 6)

array2[array2 < 7] = 1; # Filters
print(array2);

[False False False False]
[False False False False]
[False False  True  True]
[1 1 7 8]


In [23]:
# Broadcasting
# RULES
# 1. Either they have to be of same numbers
# 2. Or Either one of the number should be 1


array1 = np.array([1,2,3,4]);
array2 = np.array([[1],[2],[3],[4]]);

print(array1 * array2);

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [ ]:
# Aggregate Functions

array = np.array([
    [1,2,3,4],
    [5,6,7,8]
]);

# np.sum(array);
# np.mean(array);
# np.std() # standard deviation
# np.var() # variance
# np.min() # minimum value
# np.max() # maximum value
# np.argmin() | np.argmax() # Position of min / max value

print(np.sum(array, axis=0)); # Col
print(np.sum(array, axis=1)); # Row 


[ 6  8 10 12]
[10 26]


In [34]:
# Filtering with condition

array = np.array([10,15,20,25,30,35,40,45,50,60,90]);

array[array < 18] = 0
eligible = array[array >18]

# & , | && , ||

over30butUnder40 = array[ (array > 30) &  (array < 65)];
print(over30butUnder40);
# print(array);
# print(eligible);

[35 40 45 50 60]


In [41]:
# Random number generation

n = np.random.default_rng();

random = n.integers(low=1,high=50,size=(10,5));
print(random);

unifrom = np.random.uniform(low=1,high=50,size=(10,5));
print(unifrom);

[[ 5 19  3  5 34]
 [27 31 48 43 40]
 [24 16 49  1 43]
 [39 19 15 28 44]
 [42 10 16 21  2]
 [47 13 27 46 45]
 [ 9 25 38 33  7]
 [20 29 48 23 29]
 [43 12 37 15  9]
 [11  4 10 19 13]]
[[21.35950136 39.5407272  38.65860942 35.35577066 29.73863342]
 [44.21928615 41.57337957 18.65613151 29.72164026 21.10921232]
 [47.01713991 41.41601853 20.63710919 29.02115147 45.65993814]
 [12.70978267 24.16812886 30.050386   16.17809198 15.25603934]
 [31.3800566  29.39412658  1.56115583 43.96223724 10.49765468]
 [30.33330234 40.34072019 22.97629968 49.87113513 15.9951099 ]
 [15.18712673 48.18878771 16.53157392 46.21327933 34.08673132]
 [22.33514942 20.33000494 22.22530626 44.91519788 42.80174897]
 [30.18456331 35.25037849 25.88533193 17.43487774  5.21432039]
 [40.62526254 24.53820202 27.65256312 42.81904047 40.4896845 ]]
